---
- hosts: all
  become: true

  tasks:
  - name: removing old war file
    file:
      path: /opt/tomcat9/webapps/SpringBootMavenExample-1.3.5.RELEASE.war
      state: absent
  - name: deploy war file
    copy:
      src: /root/.jenkins/workspace/job-3/target/SpringBootMavenExample-1.3.5.RELEASE.war
      dest: /opt/tomcat9/webapps
